### ISSUE TITLE
Suggestion: Switch to "Monitoring::Plugin" instead of "Nagios::Plugin"

### ISSUE THREAD

**Issue by kentfredric** [Flameeyes/nagios-plugins-flameeyes#1]
Due to [trademark-style disputes around the latter](https://metacpan.org/pod/Nagios::Plugin#EXPLANATION), we're wanting to [nuke this](https://bugs.gentoo.org/show_bug.cgi?id=608224) from [tree in Gentoo](https://bugs.gentoo.org/show_bug.cgi?id=575986).

But naturally, this requires upstream sources to migrate the code first.

**Comment by Flameeyes** [comment]
I've not used this in at least three years, feel free to nuke the whole package or provide a pull request.
